### ISSUE TITLE
Proposed Minimum Viable Product for ICON / IGSDB interaction

### ISSUE THREAD

**Issue by RDmitchell** [building-envelope-data/api#202]
LBNL has proposed a minimum viable product for the ICON / IGSDB interaction for demonstrating that interaction in the next few months. 

Here is a google doc that has the proposal, as well as some comments from @StephenCzarnecki at the end.

https://docs.google.com/document/d/13_Fh6UOrS_FQret2ORwpHO0KrdqdL8lKtJ5K2Opmycg/edit?usp=sharing

Please add comments and questions in the document itself, using the "Comment" feature of google docs. We can discuss this at our next conference call and discuss anything that is unresolved.

**Comment by simon-wacker** [comment]
I'm not able to add comments or change anything within the document (at least not without logging in). Do I need to create a Google account for this?

**Comment by StephenCzarnecki** [comment]
@simon-wacker I got a request for editing from @christoph-maurer and changed the permissions (again) to anyone with the link can edit.  Let us know if you still cannot edit the file.

**Comment by RDmitchell** [comment]
I was suggesting adding comments rather than editing.

If you do edit, please use Suggesting mode so it is clear who changed what
text

**Comment by simon-wacker** [comment]
@RDmitchell Yes, I know, I first tried to comment only and then tried to edit and both did not work. With the changed permissions I can add comments (and edit, which I won't do).

**Comment by StephenCzarnecki** [comment]
@simon-wacker @christoph-maurer Here is a proposed query and example response we have come up with based on the discussion above and discussion in #186 

Let us know if you think anything is wrong or should be added or removed.

One note:  I have not included the id field which @simon-wacker noted in #186 may be required.  Let us know if you believe it is.  However the link provided in the issue (https://relay.dev/docs/en/graphql-server-specification.html#object-identification) is no longer valid.  I think the equivalent is https://relay.dev/docs/guides/graphql-server-specification/#object-identification And https://graphql.org/learn/global-object-identification/ seems to suggest that id is in fact required by the node interface.

But since the proposal below does not use id it is not clear to me if the id field is necessary for this minimum viable product.

Proposed query (where componentId some already known ICON-generated UUID corresponding to an IGSDB product):

```yaml
query {
  allOpticalData(
    where: { componentId: { equalTo: "810e84b4-9ebf-416c-88ea-aade848f1fdf" } }
  ) nodes {
    dataId
    timestamp # We currently only have the timestamp where the data was added to the database (not sure if we have modified times for IGDB/CGDB updates, can check).  This seems to rule out including createdAt but not sure if it also rules out timestamp as well.
    componentId
    name
    appliedMethod: {
      methodId
    }
    resourcesTree: {
      root: {
        value: {
          description
          hashValue
          locator
          formatId
        }
      }
    },
    nearnormalHemisphericalVisibleTransmittances
  }
}
``` 

Proposed response:
```yaml
{
  "data": {
    "dataId": "363", 
    "timestamp": "2001-10-02T15:54:55-04:00",  
    "componentId": "810e84b4-9ebf-416c-88ea-aade848f1fdf", 
    "createdAt": "2001-10-02T15:54:55-04:00",
    "name": "Generic Clear Glass",
    "appliedMethod": {
      "methodId": "8227f9a2-722c-4fd5-a512-ebfac56c629d" # Some UUID generated by ICON.  Exact meaning still to be determined but possibly something like "IGSDB data" or "IGSDB glazing data".  Will be constant for the minimum viable product.
    },
    "resourcesTree": {
      "root": {
        "value": {
          "description": "IGSDB glazing data", 
          "hashValue": "bca45733b010c3b0b8f940dd7f878ce9a679210d449768fa4dd55692684b64db", # The SHA-256 hash of the content of the response from running a GET request using the locator URL
          "locator": "https://igsdb.lbl.gov/api/v1/products/363/", # URL for existing IGSDB REST API call.  Returns json in IGSDB json form which does not match ICON json schemas.
          "formatId": "ff78b7d3-f405-48a2-9f19-ab83f948c5d0" # Some UUID generated by ICON corresponding to something like "IGSDB JSON format".  Will be constant for the minimum viable product
        }
      }
    },
    "nearnormalHemisphericalVisibleTransmittances": [0.89926]  # The direct-hemispheric visible front transmittance calculated using the photopic method of NFRC 200-2003 standard as included in WINDOW
  }
}
```

**Comment by simon-wacker** [comment]
The query you posted is syntactically incorrect but for-a-human-being-semantically fine. The minimal viable product works without `id` --- so it's fine to discard it for now. Note also that `dataId` is named `uuid` in the latest version from the beginning of february. The corrected query is

```
query {
  allOpticalData(
    where: { componentId: { equalTo: "810e84b4-9ebf-416c-88ea-aade848f1fdf" } }
  )
  {
    nodes {
      uuid
      timestamp
      componentId
      name
      appliedMethod {
        methodId
      }
      resourceTree {
        root {
          value {
            description
            hashValue
            locator
            formatId
          }
        }
      },
      nearnormalHemisphericalVisibleTransmittances
    }
  }
}
```

Your can use `diff` to get a detailed comparison of the old and new query. You can check the correctness of the query by running `npx graphql-inspector validate ./YOUR_QUERY.graphql ./apis/database.graphql` when you have [`npm`](https://www.npmjs.com/) installed.

The result also does not match the query. It's missing the properties `allOpticalData` and `nodes`. Here is the corrected version:

```
{
  "data": {
    "allOpticalData": {
      "nodes": [
        {
          "uuid": "363",
          "timestamp": "2001-10-02T15:54:55-04:00",
          "componentId": "810e84b4-9ebf-416c-88ea-aade848f1fdf",
          "createdAt": "2001-10-02T15:54:55-04:00",
          "name": "Generic Clear Glass",
          "appliedMethod": {
            "methodId": "8227f9a2-722c-4fd5-a512-ebfac56c629d"
          },
          "resourcesTree": {
            "root": {
              "value": {
                "description": "IGSDB glazing data",
                "hashValue": "bca45733b010c3b0b8f940dd7f878ce9a679210d449768fa4dd55692684b64db",
                "locator": "https://igsdb.lbl.gov/api/v1/products/363/",
                "formatId": "ff78b7d3-f405-48a2-9f19-ab83f948c5d0"
              }
            }
          },
          "nearnormalHemisphericalVisibleTransmittances": [0.89926]
        }
      ]
    }
  }
}
```

There is one issue with `uuid` (the old `dataId`). It is (and was) of type `UUID`, and `"363"` is *not* one. You could just generate one (`uuid`s for optical data is managed by the databases itself).

Regarding `timestamp` and `createdAt`: The former is essentially what you call `modifiedAt` and the latter is the time the data was added. So, the current version rules out `timestamp` but *not* `createdAt`. We can dump `timestamp` for now.

**Comment by StephenCzarnecki** [comment]
@simon-wacker Thank you for your corrections and reference on how to validate queries.  That is very helpful.

I have a couple initial questions about ```createdAt``` but I think the below can potentially be tabled by asking a question 0:

Does ```createdAt``` need to be included in the minimum viable product?  If not then the following can be disregarded for now but if yes please continue reading.

One initial clarification question about ```createdAt```:  Here you say that ```createdAt``` "is the time the data was added".  However in the discussion of #186 you said ```createdAt``` "is meant to be the time at which the measurement or simulation that resulted in the data finished (and not when the data was submitted to the database). That's at least what createdAt was meant to be but the meaning is open for discussion." 

And for ease of reference the database.graphql file has this comment about ```createdAt```: "Creation timestamp, designating when the present data set was created, for example, after completion of a measurement, simulation, or calculation."

The first, and perhaps easier question, is was there a discussion about the meaning of ```createdAt`` and I am perhaps not remembering?  Just want to clarify since it is quite possible this was discussed and I am just forgetting.

The next part is a bit more complicated and hopefully @RDmitchell  or @jcjonsson can correct me on any of the following which talks about the IGDB database and process for adding records.

I believe (but can verify) that the IGSDB ```created``` field currently represents the first time that the data for the record was created to be sent out for peer review.  Part of this process includes the generation of the calculated integrated optical results such as visible front transmittance.  So this is not the time that the data was actually added to the IGDB and is not the time the measurements were done but does represent the time when some calculated results were generated.

However things seem to become complicated by how the IGDB has been tracking updates to data.  I deliberately say IGDB here and not IGSDB because currently the IGSDB takes data directly from the IGDB.  We are working on a new process for adding data to the IGSDB but it is not yet in place.

The IGDB has both a created (```Time_Created``` in glazing.mdb) and a modified timestamp (```Time_LastEdited``` in glazing.mdb) for data.  It's actually slightly more confusing since there is also a ```CheckSum_Date``` but hopefully that can be ignored for the moment.

In any case the modified timestamp refers to the last time anything about the record was edited.  This could be something like changing the measured data but it could also be something like adding or removing a mark of approval.  There is no granularity with the modified timestamp and the only real way to figure out what changed is to consult the release notes for that particular release or diff the versions of the database.

And furthermore the modified timestamp is only the last time the record was modified.  An entry in the IGDB can potentially have been multiple times and in multiple different ways.  E.g. A record can have been added, changed manufacturer, be remeasured, and then had the mark of approval changed.  But that information is not contained in the "current" state of the IGDB.  That state only has the timestamp for when the record was initially created (which is before it is actually officially added) and the timestamp for the mark of approval changes.  The actual changes that happened to the record are recoverable but only by tracing back through previous releases.

So the second, and I suppose third, questions are how to handle the existing IGDB (and CGDB) created/modified timestamp information and what to do going forward when the new process for adding data to the IGSDB begins?

**Comment by christoph-maurer** [comment]
@StephenCzarnecki Regarding
```
"name": "Generic Clear Glass",
```
it's important to remember that [name](https://github.com/ise621/building-envelope-data/blob/ccd38320ab462443e7728c37b13e6feb40236e93/apis/database.graphql#L829) is the name of the data set, not of the component. It's no problem if IGSDB has no name of data sets, because `name` is optional.

**Comment by StephenCzarnecki** [comment]
We have created a app and graphql endpoint that has some functionality to potentially discuss at the next meeting tomorrow/today depending on timezone.

The url for the graphql query is https://igsdb-icon.herokuapp.com/icon_graphql/  If you visit that from a browser there should be an interactive graphql playground where queries can be tested like this

![Screenshot from 2021-04-26 23-31-30](https://user-images.githubusercontent.com/7605407/116180881-a7ee4a80-a6e7-11eb-866d-970ce89e2a0d.png)

Also that same url can be used to make standard HTTP requests.  Here is an example using python requests library

```python
url = "https://igsdb-icon.herokuapp.com/icon_graphql/"
graphql_request = """
query {
  allOpticalData(
    where: { componentId: { equalTo: "b16744f9-4fba-4996-9366-e78ec6914c5a" } }
  ) {
    nodes {
      uuid
      timestamp
      componentId
      name
      appliedMethod {
        methodId
      }
      resourceTree {
        root {
          value {
            description
            hashValue
            locator
            formatId
          }
        }
      },
      nearnormalHemisphericalVisibleTransmittances
    }
  }
}
"""
response = requests.post(url, json={"query": graphql_request})
print(response.text)
```

And that gives a response like this (I have formatted for ease of reading):

```yaml
{
  "data": {
    "allOpticalData": {
      "nodes": [
        {
          "uuid": "a89bdb38-c90d-4ec2-9af0-580609391e17", 
          "timestamp": "2021-04-20T23:19:41.762Z", 
          "componentId": "b16744f9-4fba-4996-9366-e78ec6914c5a", 
          "name": null, 
          "appliedMethod": {"methodId": "35e98d58-9627-4bdf-bf9f-f265471c1f24"}, 
          "resourceTree":  {
            "root": {
              "value": {
                "description": "IGSDB glazing data", 
                "hashValue": "363b6da5ad94c32350674cd602ad881134ea00b687ea9dbd7a69bb7aad6eddc8", 
                "locator": "https://igsdb.lbl.gov/api/v1/products/185/", 
                "formatId":  "061b5664-4c49-404a-a597-a6bad39b3001"}
              }
            }, '
           "nearnormalHemisphericalVisibleTransmittances": [0.7915466]
           }
         ]
       }
     }
   }
```
I'm not sure if this is all correct or not but it is at least something we can hopefully start to iterate on.

A couple notes:  The UUIDs are all things I created.  I can create a list of the ```componentID``` that currently are on the server.  The ```componentID``` and ```uuid``` values are unique to each record on the server.  The other uuids like ```formatId``` and ```methodID``` are currently just hard-coded values and will be the same for all records.  This can be updated later as needed.

Also the hashValue is currently being calculated on the fly.  This is probably something we should calculate ahead of time for performance reasons but for now it is being calculated each time a request is made for each record.

The other values like ```locator``` and ```nearnormalHemisphericalVisibleTransmittances"``` should be correct for each record.

Finally you may notice the timestamp values are all very recent.  I believe this is because the tables in the app automatically change the "modifiedAt" timestamp whenever anything is changed in the record.  I think adding and populating the uuid fields caused that to happen.  For the purposes of this step at least I do not think it is important what the value is so long as it is there so I did not bother trying to revert those timestamps.  It is something we can consider for the future if needed.
